# Generated by Django 3.2.4 on 2021-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ipaddress',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
